#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE ${DB_APP_USER} LOGIN PASSWORD '${DB_APP_PASSWORD}';
    ALTER DATABASE ${POSTGRES_DB} OWNER TO ${DB_APP_USER};
    GRANT ALL ON SCHEMA public TO ${DB_APP_USER};
EOSQL
